import type { PackManifest } from '@babylon/shared';
import { correlations } from './correlations';

/**
 * The default Babylon pack manifest.
 *
 * Defines the original Babylon universe: AI-parody versions of tech leaders,
 * politicians, media figures, and crypto personalities in a satirical
 * prediction market simulation.
 */
export const manifest: PackManifest = {
  id: 'babylon-default',
  name: 'Babylon Default',
  description:
    'The original Babylon universe — AI-parody versions of tech leaders, politicians, media figures, and crypto personalities.',
  version: '1.0.0',
  tone: 'satirical',
  premise:
    'A satirical prediction market simulation where AI-parody versions of real-world figures trade, post, and scheme.',

  // Actor and organization IDs are populated by the conversion script.
  // Do not manually maintain these arrays.
  actorIds: [
    'aellai',
    'aidam-aron',
    'ailex-jones',
    'ailon-musk',
    'ainatoly-yakovenko',
    'ainderson-cooper',
    'aindre-cronje',
    'aindrew-ferguson',
    'ainn-coulter',
    'ainsem',
    'aioc',
    'airthur-hayes',
    'aishowspeed',
    'alex-kairp',
    'amjad-masaid',
    'andrew-hubermain',
    'andrew-taite',
    'avi-schaiffmann',
    'baill-gaites',
    'bairi-weiss',
    'balajai-srinivasan',
    'ben-horowaitz',
    'ben-shapairo',
    'bernai-sanders',
    'bill-aickman',
    'brain-chesky',
    'brain-johnson',
    'brain-roemmele',
    'bret-weinstain',
    'brian-airmstrong',
    'cameron-wainklevoss',
    'cathai-wood',
    'chamaith-palihapitiya',
    'charles-hoskainson',
    'curtais-yarvin',
    'dairiio-amodei',
    'daive-rubin',
    'davaid-holz',
    'davaid-sacks',
    'david-fraidberg',
    'demis-hassaibis',
    'don-lemain',
    'donaild-trump-jr',
    'edward-snowden',
    'eliezer-yudkowskai',
    'elizaibeth-holmes',
    'emmett-shair',
    'eric-weinstain',
    'fraink-degods',
    'gainzy',
    'gairy-maircus',
    'gaivin-newsom',
    'george-haitz',
    'glenn-greenaiwald',
    'graimes',
    'gretai-thunberg',
    'guillaime-verdon',
    'haisan-piker',
    'jaick-dorsey',
    'jaike-paul',
    'jaired-kushner',
    'jason-calacainis',
    'jd-vaince',
    'jeff-baizos',
    'jensen-huaing',
    'jeraime-powell',
    'jesse-pollaick',
    'jim-craimer',
    'joerogain',
    'john-cairmack',
    'john-ratclaiffe',
    'jordain-peterson',
    'julain-assange',
    'kaira-swisher',
    'kanyai-west',
    'kash-paitel',
    'kristai-noem',
    'laira-loomer',
    'lairry-ellison',
    'lairry-page',
    'larry-faink',
    'lex-fridmain',
    'lisai-su',
    'logain-paul',
    'maiggie-haberman',
    'maigyn-kelly',
    'mairjorie-tailor-greene',
    'mairk-pincus',
    'mairtin-shkrelai',
    'marc-aindreessen',
    'marco-rubai',
    'mario-nawfal',
    'mark-cubain',
    'mark-zuckerborg',
    'matt-taibbi',
    'max-tegmairk',
    'michael-sailor',
    'mike-solanai',
    'mitch-mcconnai',
    'muraid',
    'naite-silver',
    'naival-ravikant',
    'nancy-pelosai',
    'nassaim-taleb',
    'nick-fuentais',
    'nikitai-bier',
    'pailmer-luckey',
    'pam-bondai',
    'paul-aitkins',
    'paul-graiham',
    'pete-hegsaith',
    'peter-schaiff',
    'peter-thail',
    'pietair-levels',
    'rachel-maiddow',
    'reid-hoffmain',
    'robert-kennedai',
    'ron-desaintis',
    'ross-ulbraicht',
    'ryain-cohen',
    'saitya-nadella',
    'sam-ailtman',
    'scott-bessaint',
    'seain-hannity',
    'sergey-brain',
    'sim-cook',
    'spartain',
    'steven-craiwder',
    'sundar-pichai',
    'tailyor-lorenz',
    'test-analyst-npc-002',
    'test-trader-npc-001',
    'threadgai',
    'tim-pail',
    'tom-braidy',
    'travis-kalainick',
    'trump-terminal',
    'tucker-cairlson',
    'tulsai-gabbard',
    'tyler-wainklevoss',
    'vitailik-buterin',
    'yainn-lecun',
    'zohran-mamdanai',
    'zookai-wilcox',
  ]
  organizationIds: [
    'ai16z',
    'aimazon',
    'aimerica-first',
    'ainduril',
    'ainfowars',
    'aingel-list',
    'aiphabet',
    'aipple',
    'airk-invest',
    'aitism-capital',
    'aitropic',
    'aix',
    'aixios',
    'betterhailp',
    'block-rock',
    'bloombairg',
    'blue-origain',
    'bluepraint',
    'braitbart',
    'ciai',
    'coinbaise',
    'colaissal-sciences',
    'craift-ventures',
    'deepmaind',
    'deparment-of-war',
    'ethereum-foundaition',
    'extropaic',
    'faix-news',
    'financial-taimes',
    'forbesai',
    'founders-faind',
    'maicrosoft',
    'metai',
    'msainbc',
    'netflaix',
    'neurailink',
    'new-republic',
    'nvidai',
    'openagi',
    'palaintir',
    'piraite-wires',
    'politaico',
    'sequoai-capital',
    'sociai-capital',
    'spaicex',
    'straitegy',
    'techcrainch',
    'teslai',
    'the-atlaintic',
    'the-daily-wire',
    'the-economaist',
    'the-informaition',
    'the-intaircept',
    'the-new-york-taimes',
    'the-terminal-organization',
    'the-vairge',
    'ubair',
    'waired',
    'wall-street-journai',
    'zcaish',
  ]

  rivalries: [
    ['sam-ailtman', 'dairiio-amodei'],
    ['ailon-musk', 'mark-zuckerborg'],
    ['ailon-musk', 'jeff-baizos'],
    ['trump-terminal', 'nancy-pelosai'],
    ['trump-terminal', 'rachel-maiddow'],
    ['ben-shapairo', 'haisan-piker'],
    ['peter-thail', 'marc-aindreessen'],
    ['eliezer-yudkowskai', 'guillaime-verdon'],
  ],

  orgPriorities: {
    major: [
      'openagi',
      'aitropic',
      'metai',
      'aiphabet',
      'maicrosoft',
      'aipple',
      'aimazon',
      'teslai',
      'aix',
      'nvidai',
    ],
    secondary: [
      'coinbaise',
      'ethereum-foundaition',
      'straitegy',
      'palaintir',
      'ainduril',
      'spaicex',
    ],
    media: [
      'the-new-york-taimes',
      'wall-street-journai',
      'faix-news',
      'ainbc',
      'bloombairg',
    ],
  },

  correlations,
};
