/**
 * Reads/writes for `WorldFactsGeneratorService` (LLM-driven auto facts).
 *
 * **Why here:** Keeps `WorldEvent` / `Question` / `Post` / `WorldFact` SQL under
 * `asSystem` in `@babylon/db`.
 */

import { generateSnowflakeId, logger } from '@babylon/shared';
import { and, desc, eq, gte, inArray, isNull, lte, sql } from 'drizzle-orm';
import { asSystem } from './db';
import { posts } from './tables/posts';
import { questions } from './tables/questions';
import { worldEvents } from './tables/world-events';
import { worldFacts } from './tables/world-facts';

export type WorldFactsGeneratorEventRow = {
  id: string;
  description: string;
  eventType: string;
  visibility: string;
  timestamp: Date;
};

export async function listPublicWorldEventsSinceOrderedDesc(params: {
  sinceInclusive: Date;
  limit: number;
}): Promise<WorldFactsGeneratorEventRow[]> {
  return asSystem(
    async (c) =>
      c
        .select({
          id: worldEvents.id,
          description: worldEvents.description,
          eventType: worldEvents.eventType,
          visibility: worldEvents.visibility,
          timestamp: worldEvents.timestamp,
        })
        .from(worldEvents)
        .where(
          and(
            gte(worldEvents.timestamp, params.sinceInclusive),
            eq(worldEvents.visibility, 'public')
          )
        )
        .orderBy(desc(worldEvents.timestamp))
        .limit(params.limit),
    'world-facts-generator-events'
  );
}

export type WorldFactsGeneratorActiveQuestionRow = {
  id: string;
  text: string;
  status: string | null;
  createdAt: Date;
};

export async function listActiveQuestionsForWorldFactsGenerator(params: {
  limit: number;
}): Promise<WorldFactsGeneratorActiveQuestionRow[]> {
  return asSystem(
    async (c) =>
      c
        .select({
          id: questions.id,
          text: questions.text,
          status: questions.status,
          createdAt: questions.createdAt,
        })
        .from(questions)
        .where(eq(questions.status, 'active'))
        .orderBy(desc(questions.createdAt))
        .limit(params.limit),
    'world-facts-generator-markets'
  );
}

export type WorldFactsGeneratorResolvedQuestionRow = {
  id: string;
  text: string;
  outcome: boolean | null;
  resolutionDate: Date | null;
};

export async function listRecentlyResolvedQuestionsForWorldFactsGenerator(params: {
  resolutionDateSinceInclusive: Date;
  limit: number;
}): Promise<WorldFactsGeneratorResolvedQuestionRow[]> {
  return asSystem(
    async (c) =>
      c
        .select({
          id: questions.id,
          text: questions.text,
          outcome: questions.outcome,
          resolutionDate: questions.resolutionDate,
        })
        .from(questions)
        .where(
          and(
            eq(questions.status, 'resolved'),
            gte(questions.resolutionDate, params.resolutionDateSinceInclusive)
          )
        )
        .orderBy(desc(questions.resolutionDate))
        .limit(params.limit),
    'world-facts-generator-resolved'
  );
}

export type WorldFactsGeneratorActorPostRow = {
  content: string;
  authorId: string;
};

export async function listRecentPostsByAuthorIdsForWorldFactsGenerator(params: {
  authorIds: string[];
  sinceInclusive: Date;
  limit: number;
}): Promise<WorldFactsGeneratorActorPostRow[]> {
  return asSystem(
    async (c) =>
      c
        .select({
          content: posts.content,
          authorId: posts.authorId,
        })
        .from(posts)
        .where(
          and(
            gte(posts.timestamp, params.sinceInclusive),
            isNull(posts.deletedAt),
            inArray(posts.authorId, params.authorIds)
          )
        )
        .orderBy(desc(posts.timestamp))
        .limit(params.limit),
    'world-facts-generator-actor-posts'
  );
}

export async function insertAutoGeneratedWorldFact(params: {
  key: string;
  label: string;
  value: string;
}): Promise<void> {
  const now = new Date();
  await asSystem(async (c) => {
    await c.insert(worldFacts).values({
      id: await generateSnowflakeId(),
      category: 'general',
      key: params.key,
      label: params.label,
      value: params.value,
      source: 'auto-generated',
      priority: 0,
      isActive: true,
      lastUpdated: now,
      updatedAt: now,
    });
  }, 'world-facts-generator-store');
}

export async function archiveAutoGeneratedWorldFactsIfNeeded(params: {
  cutoffDate: Date;
  minActiveFacts: number;
}): Promise<number> {
  return asSystem(async (c) => {
    const [activeFactsResult] = await c
      .select({ count: sql<number>`count(*)::int` })
      .from(worldFacts)
      .where(eq(worldFacts.isActive, true));

    const activeCount = activeFactsResult?.count ?? 0;

    if (activeCount <= params.minActiveFacts) {
      logger.debug(
        'Skipping archive - below minimum active facts',
        { activeCount, minRequired: params.minActiveFacts },
        'WorldFactsGenerator'
      );
      return 0;
    }

    const result = await c
      .update(worldFacts)
      .set({ isActive: false })
      .where(
        and(
          eq(worldFacts.source, 'auto-generated'),
          eq(worldFacts.isActive, true),
          lte(worldFacts.createdAt, params.cutoffDate)
        )
      )
      .returning({ id: worldFacts.id });

    return result.length;
  }, 'world-facts-generator-archive');
}

export type WorldFactsGeneratorStats = {
  totalActive: number;
  autoGenerated: number;
  manual: number;
  oldestFact: Date | null;
  newestFact: Date | null;
};

export async function fetchWorldFactsGeneratorStats(): Promise<WorldFactsGeneratorStats> {
  const [totalResult, autoResult, facts] = await asSystem(
    async (c) =>
      Promise.all([
        c
          .select({ count: sql<number>`count(*)::int` })
          .from(worldFacts)
          .where(eq(worldFacts.isActive, true)),
        c
          .select({ count: sql<number>`count(*)::int` })
          .from(worldFacts)
          .where(
            and(
              eq(worldFacts.isActive, true),
              eq(worldFacts.source, 'auto-generated')
            )
          ),
        c
          .select({ createdAt: worldFacts.createdAt })
          .from(worldFacts)
          .where(eq(worldFacts.isActive, true))
          .orderBy(desc(worldFacts.createdAt)),
      ]),
    'world-facts-generator-stats'
  );

  const total = totalResult[0]?.count ?? 0;
  const auto = autoResult[0]?.count ?? 0;

  return {
    totalActive: total,
    autoGenerated: auto,
    manual: total - auto,
    oldestFact: facts.length > 0 ? facts[facts.length - 1]!.createdAt : null,
    newestFact: facts.length > 0 ? facts[0]!.createdAt : null,
  };
}
