/**
 * World Facts Generator Service
 *
 * Automatically generates new world facts and context from game events,
 * market activity, and question resolutions. Keeps the game world fresh
 * and prevents content repetition.
 *
 * @module services/world-facts-generator
 */

import {
  archiveAutoGeneratedWorldFactsIfNeeded,
  fetchWorldFactsGeneratorStats,
  insertAutoGeneratedWorldFact,
  listActiveQuestionsForWorldFactsGenerator,
  listPublicWorldEventsSinceOrderedDesc,
  listRecentlyResolvedQuestionsForWorldFactsGenerator,
  listRecentPostsByAuthorIdsForWorldFactsGenerator,
} from '@babylon/db';
import { logger } from '@babylon/shared';
import { BabylonLLMClient } from '../llm/openai-client';
import { StaticDataRegistry } from './static-data-registry';

/**
 * Configuration for world facts generation
 */
export interface WorldFactsGenerationConfig {
  /** Maximum new facts to generate per update */
  maxFactsPerUpdate: number;
  /** Maximum age of facts to keep (in days) */
  maxFactAgeDays: number;
  /** Minimum facts to maintain active */
  minActiveFacts: number;
}

const DEFAULT_CONFIG: WorldFactsGenerationConfig = {
  maxFactsPerUpdate: 10,
  maxFactAgeDays: 7,
  minActiveFacts: 20,
};

/**
 * World Facts Generator Service
 *
 * Creates dynamic world context based on game activity to prevent
 * content staleness and repetition.
 */
export class WorldFactsGeneratorService {
  private config: WorldFactsGenerationConfig;
  private llm: BabylonLLMClient;

  constructor(
    config: Partial<WorldFactsGenerationConfig> = {},
    llm?: BabylonLLMClient
  ) {
    this.config = { ...DEFAULT_CONFIG, ...config };
    this.llm = llm ?? BabylonLLMClient.forGameTick();
  }

  /**
   * Generate new world facts from recent game activity
   *
   * This is the main entry point - call this periodically (e.g., every 12 hours)
   * to keep the world context fresh.
   */
  async generateNewWorldFacts(): Promise<{
    generated: number;
    archived: number;
    sources: {
      events: number;
      markets: number;
      questions: number;
      actors: number;
    };
  }> {
    const startTime = Date.now();
    logger.info(
      'Starting world facts generation',
      undefined,
      'WorldFactsGenerator'
    );

    // Gather context from different sources
    const [eventFacts, marketFacts, questionFacts, actorFacts] =
      await Promise.all([
        this.generateFactsFromEvents(),
        this.generateFactsFromMarketActivity(),
        this.generateFactsFromQuestions(),
        this.generateFactsFromActorActivity(),
      ]);

    // Combine and deduplicate
    const allNewFacts = [
      ...eventFacts,
      ...marketFacts,
      ...questionFacts,
      ...actorFacts,
    ];

    // Store the new facts
    let storedCount = 0;
    for (const fact of allNewFacts.slice(0, this.config.maxFactsPerUpdate)) {
      try {
        await this.storeFact(fact);
        storedCount++;
      } catch (error) {
        logger.warn(
          'Failed to store world fact',
          { fact, error },
          'WorldFactsGenerator'
        );
      }
    }

    // Archive old facts
    const archivedCount = await this.archiveOldFacts();

    const duration = Date.now() - startTime;
    logger.info(
      'World facts generation complete',
      {
        generated: storedCount,
        archived: archivedCount,
        duration,
        sources: {
          events: eventFacts.length,
          markets: marketFacts.length,
          questions: questionFacts.length,
          actors: actorFacts.length,
        },
      },
      'WorldFactsGenerator'
    );

    return {
      generated: storedCount,
      archived: archivedCount,
      sources: {
        events: eventFacts.length,
        markets: marketFacts.length,
        questions: questionFacts.length,
        actors: actorFacts.length,
      },
    };
  }

  /**
   * Generate facts from recent world events
   * Uses 48-hour window to capture more activity across game day boundaries
   */
  private async generateFactsFromEvents(): Promise<string[]> {
    const twoDaysAgo = new Date(Date.now() - 48 * 60 * 60 * 1000);

    const recentEvents = await listPublicWorldEventsSinceOrderedDesc({
      sinceInclusive: twoDaysAgo,
      limit: 10,
    });

    if (recentEvents.length === 0) {
      return [];
    }

    // Use LLM to synthesize events into world facts
    const eventDescriptions = recentEvents
      .map((e) => `- ${e.description}`)
      .join('\n');

    const prompt = `Based on these recent events in our satirical AI-powered world, generate 2-3 world facts that capture the current state of affairs. These facts should be reusable context for future content generation.

RECENT EVENTS:
${eventDescriptions}

Generate facts that:
- Summarize trends or developments (not individual events)
- Can be used as context for market discussions, NPC posts, and news articles
- Feel like "background knowledge" about the current world state
- Use parody names (AIlon Musk, Sam AIltman, OpenAGI, etc.)

Return as XML:
<response>
  <facts>
    <fact>First world fact here</fact>
    <fact>Second world fact here</fact>
  </facts>
</response>`;

    try {
      const response = await this.llm.generateJSON<
        { facts: string[] } | { response: { facts: string[] } }
      >(
        prompt,
        {
          properties: {
            facts: {
              type: 'array',
              items: { type: 'string' },
            },
          },
          required: ['facts'],
        },
        {
          temperature: 0.8,
          maxTokens: 500,
          format: 'xml',
          promptType: 'world_facts_from_events',
        }
      );

      const facts =
        'response' in response ? response.response.facts : response.facts;
      return Array.isArray(facts)
        ? facts.filter((f) => f && f.length > 10)
        : [];
    } catch (error) {
      logger.error(
        'Failed to generate facts from events',
        { error },
        'WorldFactsGenerator'
      );
      return [];
    }
  }

  /**
   * Generate facts from market activity and trends
   */
  private async generateFactsFromMarketActivity(): Promise<string[]> {
    // Get active questions with market data
    const activeQuestions = await listActiveQuestionsForWorldFactsGenerator({
      limit: 5,
    });

    if (activeQuestions.length === 0) {
      return [];
    }

    const questionList = activeQuestions.map((q) => `- "${q.text}"`).join('\n');

    const prompt = `Based on these active prediction markets in our satirical AI world, generate 1-2 world facts about what people are betting on and the current mood/sentiment.

ACTIVE PREDICTION MARKETS:
${questionList}

Generate facts that:
- Capture what the market is focused on
- Reflect the speculative nature of the world
- Can be used as context for discussions
- Use parody names (AIlon Musk, Sam AIltman, OpenAGI, etc.)

Return as XML:
<response>
  <facts>
    <fact>Market sentiment or trend fact here</fact>
  </facts>
</response>`;

    try {
      const response = await this.llm.generateJSON<
        { facts: string[] } | { response: { facts: string[] } }
      >(
        prompt,
        {
          properties: {
            facts: {
              type: 'array',
              items: { type: 'string' },
            },
          },
          required: ['facts'],
        },
        {
          temperature: 0.8,
          maxTokens: 400,
          format: 'xml',
          promptType: 'world_facts_from_markets',
        }
      );

      const facts =
        'response' in response ? response.response.facts : response.facts;
      return Array.isArray(facts)
        ? facts.filter((f) => f && f.length > 10)
        : [];
    } catch (error) {
      logger.error(
        'Failed to generate facts from markets',
        { error },
        'WorldFactsGenerator'
      );
      return [];
    }
  }

  /**
   * Generate facts from recently resolved questions
   * Uses 7-day window to capture more question resolutions
   */
  private async generateFactsFromQuestions(): Promise<string[]> {
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);

    const recentlyResolved =
      await listRecentlyResolvedQuestionsForWorldFactsGenerator({
        resolutionDateSinceInclusive: sevenDaysAgo,
        limit: 5,
      });

    if (recentlyResolved.length === 0) {
      return [];
    }

    const facts: string[] = [];
    for (const q of recentlyResolved) {
      // Skip items with null/undefined outcomes
      if (q.outcome == null) {
        continue;
      }
      const outcomeText = q.outcome ? 'YES' : 'NO';
      // Create a simple fact about the resolution
      facts.push(
        `The prediction market "${q.text}" resolved to ${outcomeText}, which has implications for related markets and discussions.`
      );
    }

    return facts.slice(0, 2);
  }

  /**
   * Generate facts about actor activities and relationships
   * Uses 48-hour window to capture more actor activity
   */
  private async generateFactsFromActorActivity(): Promise<string[]> {
    // Get recent posts from main actors
    const twoDaysAgo = new Date(Date.now() - 48 * 60 * 60 * 1000);

    // Get main actors
    const mainActors = StaticDataRegistry.getAllActors()
      .filter((a) => a.role === 'main' || a.tier === 'S_TIER')
      .slice(0, 5);

    if (mainActors.length === 0) {
      return [];
    }

    const actorIds = mainActors.map((a) => a.id);

    // Get their recent posts (filter by actorIds in the query to avoid unnecessary data transfer)
    const actorPosts = await listRecentPostsByAuthorIdsForWorldFactsGenerator({
      authorIds: actorIds,
      sinceInclusive: twoDaysAgo,
      limit: 20,
    });

    if (actorPosts.length === 0) {
      return [];
    }

    const postSamples = actorPosts
      .slice(0, 5)
      .map((p) => `- ${p.content.substring(0, 100)}...`)
      .join('\n');

    const prompt = `Based on recent activity from key figures in our satirical AI world, generate 1-2 world facts about current topics of discussion or emerging narratives.

RECENT POSTS FROM KEY FIGURES:
${postSamples}

Generate facts that:
- Capture what the key figures are focused on
- Identify emerging topics or debates
- Can be used as context for other content
- Use parody names (AIlon Musk, Sam AIltman, OpenAGI, etc.)

Return as XML:
<response>
  <facts>
    <fact>Topic or narrative fact here</fact>
  </facts>
</response>`;

    try {
      const response = await this.llm.generateJSON<
        { facts: string[] } | { response: { facts: string[] } }
      >(
        prompt,
        {
          properties: {
            facts: {
              type: 'array',
              items: { type: 'string' },
            },
          },
          required: ['facts'],
        },
        {
          temperature: 0.8,
          maxTokens: 400,
          format: 'xml',
          promptType: 'world_facts_from_actors',
        }
      );

      const facts =
        'response' in response ? response.response.facts : response.facts;
      return Array.isArray(facts)
        ? facts.filter((f) => f && f.length > 10)
        : [];
    } catch (error) {
      logger.error(
        'Failed to generate facts from actors',
        { error },
        'WorldFactsGenerator'
      );
      return [];
    }
  }

  /**
   * Store a new world fact in the database
   */
  private async storeFact(value: string): Promise<void> {
    // Generate a key from the first few words
    let keyWords = value
      .toLowerCase()
      .split(/\s+/)
      .slice(0, 5)
      .join('_')
      .replace(/[^a-z0-9_]/g, '')
      .substring(0, 50);

    // Fallback if keyWords is empty (e.g., value has only non-alphanumerics)
    if (!keyWords) {
      // Use a short hash derived from the value for uniqueness
      const hash = value
        .split('')
        .reduce((acc, char) => ((acc << 5) - acc + char.charCodeAt(0)) | 0, 0);
      keyWords = `fact_${Math.abs(hash).toString(36)}`;
    }

    const key = `dynamic_${keyWords}_${Date.now()}`;
    const label = value.length > 60 ? value.substring(0, 57) + '...' : value;

    await insertAutoGeneratedWorldFact({ key, label, value });
  }

  /**
   * Archive old facts to keep the context fresh
   */
  private async archiveOldFacts(): Promise<number> {
    const cutoffDate = new Date(
      Date.now() - this.config.maxFactAgeDays * 24 * 60 * 60 * 1000
    );

    return archiveAutoGeneratedWorldFactsIfNeeded({
      cutoffDate,
      minActiveFacts: this.config.minActiveFacts,
    });
  }

  /**
   * Generate a quick summary of the current world state
   * Useful for status checks
   */
  async getWorldFactsStats(): Promise<{
    totalActive: number;
    autoGenerated: number;
    manual: number;
    oldestFact: Date | null;
    newestFact: Date | null;
  }> {
    return fetchWorldFactsGeneratorStats();
  }
}

// Singleton instance
export const worldFactsGenerator = new WorldFactsGeneratorService();

/**
 * Create a custom world facts generator
 */
export function createWorldFactsGenerator(
  config?: Partial<WorldFactsGenerationConfig>,
  llm?: BabylonLLMClient
): WorldFactsGeneratorService {
  return new WorldFactsGeneratorService(config, llm);
}
