/**
 * Relationship Evolution Engine
 *
 * Manages dynamic NPC relationships that evolve based on in-game interactions.
 * Uses simple TEXT descriptions instead of complex numerical systems.
 *
 * Philosophy: "AIlon hates Zuckerborg for that thing he did on Titan"
 * - Simple text descriptions
 * - Generated by LLM based on interactions
 * - Evolves naturally over time
 * - No complex matrices or calculations
 */

import {
  actorRelationships,
  and,
  db,
  desc,
  eq,
  gte,
  npcInteractions,
  or,
} from '@babylon/db'
import {
  generateSnowflakeId,
  logger,
  RelationshipDescriptionSchema,
  toDate,
} from '@babylon/shared'
import type { BabylonLLMClient } from './llm/openai-client'
import { StaticDataRegistry } from './services/static-data-registry'
import type { Actor, ActorRelationship, Organization } from './types/shared'

// Note: Row types are accessed via direct property coercion to avoid cast requirements

export interface RelationshipChange {
  actor1Id: string
  actor2Id: string
  action: 'create' | 'update' | 'delete'
  newHistory?: string // The text description
  newType?: string
  newSentiment?: number
  newStrength?: number
  reason: string
}

export interface Interaction {
  actor1Id: string
  actor2Id: string
  type: 'mention' | 'reply' | 'article' | 'event' | 'trade'
  sentiment: number
  context: string
  timestamp: Date
}

export class RelationshipEvolutionEngine {
  constructor(private llm?: BabylonLLMClient) {}

  /**
   * Generate initial relationships on first game tick
   * Simple algorithm based on affiliations and domains
   */
  async generateInitialRelationships(
    actors: Actor[],
    organizations: Organization[],
  ): Promise<number> {
    logger.info(
      'Generating initial NPC relationships...',
      undefined,
      'RelationshipEvolutionEngine',
    )

    let created = 0
    const orgMap = new Map(organizations.map((o) => [o.id, o]))

    // Simple algorithm: Create relationships between actors with shared context
    for (let i = 0; i < actors.length; i++) {
      const actor1 = actors[i]
      if (!actor1) continue

      // Each actor gets 3-8 relationships
      const targetCount = 3 + Math.floor(Math.random() * 6)
      let relationshipCount = 0

      for (
        let j = i + 1;
        j < actors.length && relationshipCount < targetCount;
        j++
      ) {
        const actor2 = actors[j]
        if (!actor2) continue

        // Calculate simple compatibility
        const sharedOrgs =
          actor1.affiliations?.filter((org) =>
            actor2.affiliations?.includes(org),
          ) || []

        const sharedDomains =
          actor1.domain?.filter((d) => actor2.domain?.includes(d)) || []

        const hasSharedContext =
          sharedOrgs.length > 0 || sharedDomains.length > 0
        const randomChance = Math.random() > 0.7 // 30% chance even without shared context

        if (hasSharedContext || randomChance) {
          // Generate simple text description using LLM if available, otherwise use templates
          let history: string
          let type: string
          let sentiment: number

          if (this.llm && sharedOrgs.length > 0 && sharedOrgs[0]) {
            // LLM-DRIVEN: Generate relationship from context
            const org = orgMap.get(sharedOrgs[0])
            const context = `both affiliated with ${org?.name || 'same organization'}`

            // Check if relationship already exists
            const existingRows = await db
              .select()
              .from(actorRelationships)
              .where(
                or(
                  and(
                    eq(actorRelationships.actor1Id, actor1.id),
                    eq(actorRelationships.actor2Id, actor2.id),
                  ),
                  and(
                    eq(actorRelationships.actor1Id, actor2.id),
                    eq(actorRelationships.actor2Id, actor1.id),
                  ),
                ),
              )
              .limit(1)
            const existingRow = existingRows[0]
            const existingHistory = existingRow?.history
              ? String(existingRow.history)
              : undefined

            const llmResult = await this.generateInitialRelationshipDescription(
              actor1.name,
              actor2.name,
              context,
              actor1.personality || '',
              actor2.personality || '',
              existingHistory,
            )

            history = llmResult.description
            type = llmResult.type
            sentiment = llmResult.sentiment
          } else if (sharedOrgs.length > 0 && sharedOrgs[0]) {
            // Fallback: Simple template
            const org = orgMap.get(sharedOrgs[0])
            const orgName = org?.name.toLowerCase() || 'same company'
            history = `both work at ${orgName}`
            type = 'acquaintances'
            sentiment = Math.random() * 0.6 - 0.3
          } else if (sharedDomains.length > 0) {
            history = `both work in ${sharedDomains[0]}`
            type = 'acquaintances'
            sentiment = Math.random() * 0.4 - 0.2
          } else {
            history = 'professional circles'
            type = 'acquaintances'
            sentiment = 0
          }

          // Create relationship (use insert with conflict handling to avoid duplicates)
          // Check if relationship already exists first
          const existingRelRows = await db
            .select({ id: actorRelationships.id })
            .from(actorRelationships)
            .where(
              or(
                and(
                  eq(actorRelationships.actor1Id, actor1.id),
                  eq(actorRelationships.actor2Id, actor2.id),
                ),
                and(
                  eq(actorRelationships.actor1Id, actor2.id),
                  eq(actorRelationships.actor2Id, actor1.id),
                ),
              ),
            )
            .limit(1)
          const existingRelId = existingRelRows[0]?.id

          if (!existingRelId) {
            await db.insert(actorRelationships).values({
              id: await generateSnowflakeId(),
              actor1Id: actor1.id,
              actor2Id: actor2.id,
              relationshipType: type,
              strength: 0.3 + Math.random() * 0.5,
              sentiment,
              history,
              isPublic: true,
              updatedAt: new Date(),
              interactionCount: 0,
              evolutionCount: 0,
            })
          }

          created++
          relationshipCount++
        }
      }
    }

    logger.info(
      `Created ${created} initial relationships`,
      { count: created },
      'RelationshipEvolutionEngine',
    )
    return created
  }

  /**
   * Generate initial relationship description using LLM (emergent, not hardcoded)
   */
  private async generateInitialRelationshipDescription(
    actor1Name: string,
    actor2Name: string,
    context: string,
    personality1: string,
    personality2: string,
    existingRelationship?: string,
  ): Promise<{ description: string; type: string; sentiment: number }> {
    const prompt = `Analyze the relationship between two NPCs:

NPC 1: ${actor1Name} (${personality1})
NPC 2: ${actor2Name} (${personality2})
Context: ${context}
${existingRelationship ? `Previous relationship: ${existingRelationship}` : 'No previous relationship'}

Write a natural, casual description of their relationship. Be specific and narrative.

Examples of good descriptions:
- "competing for dominance after that ai board drama"
- "allies since working together on the rocket launch"
- "professional acquaintances in the tech scene"
- "used to work together but had a falling out over patents"

Guidelines:
- Keep it lowercase and casual
- Be specific to events/context when possible
- Around 100-200 characters is ideal (but can be longer if needed for context)
- Natural narrative style

Also determine:
- Type: allies, rivals, friends, enemies, acquaintances, or neutral
- Sentiment: -1.0 (hostile) to 1.0 (friendly)

Return JSON: { "description": "...", "type": "...", "sentiment": 0.0 }`

    const response = await this.llm?.generateJSON<{
      description: string
      type: string
      sentiment: number
    }>(
      prompt,
      { required: ['description', 'type', 'sentiment'] },
      { maxTokens: 200, temperature: 0.9 },
    )

    if (!response) {
      return {
        description: 'professional acquaintances',
        type: 'acquaintances',
        sentiment: 0,
      }
    }

    return {
      description: response.description.toLowerCase().trim(),
      type: response.type || 'acquaintances',
      sentiment: Math.max(-1, Math.min(1, response.sentiment || 0)),
    }
  }

  /**
   * Track an interaction between two NPCs
   */
  async trackInteraction(
    interaction: Omit<Interaction, 'timestamp'>,
  ): Promise<void> {
    // Sort IDs to ensure consistency
    const sorted = [interaction.actor1Id, interaction.actor2Id].sort()
    const id1 = sorted[0]
    const id2 = sorted[1]

    await db.insert(npcInteractions).values({
      id: await generateSnowflakeId(),
      actor1Id: id1,
      actor2Id: id2,
      interactionType: interaction.type,
      sentiment: interaction.sentiment,
      context: interaction.context,
      timestamp: new Date(),
    })
  }

  /**
   * Analyze recent interactions and generate relationship updates using LLM
   * This is the KEY method - uses LLM to generate natural text descriptions
   */
  async analyzeAndUpdateRelationships(): Promise<number> {
    if (!this.llm) {
      logger.warn(
        'No LLM client available, skipping relationship analysis',
        undefined,
        'RelationshipEvolutionEngine',
      )
      return 0
    }

    // Get recent interactions (last 7 days)
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
    const recentInteractionsRaw = await db
      .select()
      .from(npcInteractions)
      .where(gte(npcInteractions.timestamp, sevenDaysAgo))
      .orderBy(desc(npcInteractions.timestamp))
      .limit(100) // Limit to prevent token overflow

    // Map interactions with proper type coercion
    const recentInteractions = recentInteractionsRaw
      .filter((row): row is NonNullable<typeof row> => row != null)
      .map((row) => ({
        id: String(row.id ?? ''),
        actor1Id: row.actor1Id != null ? String(row.actor1Id) : null,
        actor2Id: row.actor2Id != null ? String(row.actor2Id) : null,
        interactionType:
          row.interactionType != null ? String(row.interactionType) : null,
        sentiment: row.sentiment != null ? Number(row.sentiment) : null,
        context: row.context != null ? String(row.context) : null,
        timestamp:
          row.timestamp instanceof Date
            ? row.timestamp
            : row.timestamp
              ? new Date(String(row.timestamp))
              : null,
      }))

    if (recentInteractions.length === 0) {
      logger.info(
        'No recent interactions to analyze',
        undefined,
        'RelationshipEvolutionEngine',
      )
      return 0
    }

    type InteractionRow = (typeof recentInteractions)[number]

    // Group interactions by actor pair
    const pairInteractions = new Map<string, InteractionRow[]>()

    for (const interaction of recentInteractions) {
      const pairKey = `${interaction.actor1Id}_${interaction.actor2Id}`
      if (!pairInteractions.has(pairKey)) {
        pairInteractions.set(pairKey, [])
      }
      pairInteractions.get(pairKey)?.push(interaction)
    }

    logger.info(
      `Analyzing ${pairInteractions.size} actor pairs for relationship changes`,
      {
        pairs: pairInteractions.size,
        interactions: recentInteractions.length,
      },
      'RelationshipEvolutionEngine',
    )

    let updated = 0

    // Process each pair
    for (const [pairKey, interactions] of Array.from(pairInteractions)) {
      // Need at least 2 interactions to update relationship
      if (interactions.length < 2) continue

      const [actor1Id, actor2Id] = pairKey.split('_')
      if (!actor1Id || !actor2Id) continue

      // Get existing relationship
      const existingRows = await db
        .select()
        .from(actorRelationships)
        .where(
          and(
            eq(actorRelationships.actor1Id, actor1Id),
            eq(actorRelationships.actor2Id, actor2Id),
          ),
        )
        .limit(1)
      const existingRow = existingRows[0]
      const existingHistory = existingRow?.history
        ? String(existingRow.history)
        : null

      // Get actor names from static registry
      const actor1 = StaticDataRegistry.getActor(actor1Id)
      const actor2 = StaticDataRegistry.getActor(actor2Id)

      if (!actor1 || !actor2) continue

      // Calculate average sentiment
      const avgSentiment =
        interactions.reduce((sum, i) => sum + Number(i.sentiment ?? 0), 0) /
        interactions.length

      // Build context for LLM
      const interactionSummary = interactions
        .slice(0, 5)
        .map((i) => {
          const sentiment = Number(i.sentiment ?? 0)
          return `- ${i.interactionType}: ${i.context} (sentiment: ${sentiment > 0 ? '+' : ''}${sentiment.toFixed(2)})`
        })
        .join('\n')

      // Use LLM to generate natural text description with retry logic
      const prompt = `Analyze the evolving relationship between two NPCs based on their recent interactions.

NPC 1: ${actor1.name}
NPC 2: ${actor2.name}

Recent interactions (last 7 days):
${interactionSummary}

${existingHistory ? `Current relationship: "${existingHistory}"` : 'No existing relationship'}

Based on these interactions, write a natural, casual description of how their relationship has evolved.

Guidelines:
- Lowercase and casual tone
- Specific to recent events when possible
- Natural narrative style (not telegraphic)
- Around 100-200 characters is good (but can be longer if the story needs it)
- Reference what actually happened

Examples:
- "used to compete but now working together after that ai safety thing"
- "allies since they collaborated on the teslai rocket launch last month"
- "hates each other now after that metaverse disaster and twitter drama"
- "professional relationship that's gotten tense after competing bids"

Also determine:
- Type: allies, rivals, friends, enemies, acquaintances, or neutral
- Sentiment: -1.0 (hostile) to 1.0 (friendly)

Return JSON: { "description": "...", "type": "...", "sentiment": 0.0 }`

      // Retry logic: up to 3 attempts with LLM-generated relationship updates
      let newHistory = 'professional relationship'
      let newType = 'acquaintances'
      let newSentiment = avgSentiment
      const maxRetries = 3

      for (let attempt = 0; attempt < maxRetries; attempt++) {
        const rawResponse = await this.llm.generateJSON<{
          description: string
          type: string
          sentiment: number
        }>(
          prompt,
          { required: ['description', 'type', 'sentiment'] },
          {
            maxTokens: 200,
            temperature: 0.8,
            promptType: 'relationship_evolve',
          },
        )

        // Validate response using Zod schema
        const parseResult = RelationshipDescriptionSchema.safeParse(rawResponse)
        if (!parseResult.success) {
          logger.warn(
            'Relationship update failed validation',
            {
              error: parseResult.error.message,
              actor1: actor1.name,
              actor2: actor2.name,
            },
            'RelationshipEvolutionEngine',
          )
        }

        if (
          rawResponse.description &&
          rawResponse.description.trim().length > 0
        ) {
          // LLM determines everything - no hardcoded rules
          // Don't trim - let LLM decide length (they know the context)
          newHistory = rawResponse.description.toLowerCase().trim()
          newType = rawResponse.type || 'acquaintances'
          newSentiment = Math.max(
            -1,
            Math.min(1, rawResponse.sentiment || avgSentiment),
          )
          break // Success
        }

        // Wait before retry (exponential backoff)
        if (attempt < maxRetries - 1) {
          await new Promise((resolve) =>
            setTimeout(resolve, 1000 * 2 ** attempt),
          )
        }
      }

      // Update or create relationship
      if (existingRow) {
        // Update existing
        await db
          .update(actorRelationships)
          .set({
            history: newHistory,
            relationshipType: newType,
            sentiment: newSentiment,
            strength: Math.min(
              1.0,
              Number(existingRow.strength ?? 0.5) + interactions.length * 0.05,
            ),
            lastInteraction: new Date(),
            interactionCount:
              Number(existingRow.interactionCount ?? 0) + interactions.length,
            evolutionCount: Number(existingRow.evolutionCount ?? 0) + 1,
            updatedAt: new Date(),
          })
          .where(eq(actorRelationships.id, String(existingRow.id)))
      } else {
        // Create new
        await db.insert(actorRelationships).values({
          id: await generateSnowflakeId(),
          actor1Id,
          actor2Id,
          relationshipType: newType,
          strength: Math.min(0.7, interactions.length * 0.1),
          sentiment: newSentiment,
          history: newHistory,
          isPublic: true,
          lastInteraction: new Date(),
          interactionCount: interactions.length,
          evolutionCount: 0,
          updatedAt: new Date(),
        })
      }

      updated++
      logger.info(
        'Updated relationship',
        {
          actor1: actor1.name,
          actor2: actor2.name,
          description: newHistory,
          type: newType,
          sentiment: newSentiment.toFixed(2),
        },
        'RelationshipEvolutionEngine',
      )
    }

    logger.info(
      `Updated ${updated} relationships`,
      { count: updated },
      'RelationshipEvolutionEngine',
    )
    return updated
  }

  /**
   * Get relationship context for prompts - ULTRA SIMPLE
   * Just the text descriptions, nothing else
   */
  async getRelationshipContextForActor(actorId: string): Promise<string> {
    // Get relationships for this actor
    const relationshipsRaw = await db
      .select()
      .from(actorRelationships)
      .where(
        or(
          eq(actorRelationships.actor1Id, actorId),
          eq(actorRelationships.actor2Id, actorId),
        ),
      )
      .orderBy(desc(actorRelationships.strength))
      .limit(5) // Top 5 strongest only (keep it short)

    // Map relationships with proper type coercion
    const relationships = relationshipsRaw
      .filter((row): row is NonNullable<typeof row> => row != null)
      .map((row) => ({
        actor1Id: row.actor1Id != null ? String(row.actor1Id) : null,
        actor2Id: row.actor2Id != null ? String(row.actor2Id) : null,
        history: row.history != null ? String(row.history) : null,
      }))

    if (relationships.length === 0) {
      return ''
    }

    // Get the other actor IDs we need to look up
    const otherActorIds = relationships.map((rel) =>
      rel.actor1Id === actorId ? rel.actor2Id : rel.actor1Id,
    )

    // Get actor names from static registry
    const actorNameMap = new Map(
      otherActorIds.map((id) => {
        const actor = StaticDataRegistry.getActor(String(id))
        return [id, actor?.name || 'Unknown']
      }),
    )

    // SIMPLEST FORMAT: Just list the relationships
    const lines = relationships.map((rel) => {
      const otherActorId =
        rel.actor1Id === actorId ? rel.actor2Id : rel.actor1Id
      const otherActorName = actorNameMap.get(otherActorId) || 'Unknown'

      // Just the text description, no emojis or extra formatting
      return `- ${otherActorName}: ${rel.history || 'professional relationship'}`
    })

    return lines.join('\n')
  }

  // =============================================================================
  // STATIC QUERY METHODS (consolidated from RelationshipManager)
  // =============================================================================

  /**
   * Get all relationships for an actor (static method for queries)
   */
  static async getActorRelationships(
    actorId: string,
  ): Promise<ActorRelationship[]> {
    const relationshipsRaw = await db
      .select()
      .from(actorRelationships)
      .where(
        or(
          eq(actorRelationships.actor1Id, actorId),
          eq(actorRelationships.actor2Id, actorId),
        ),
      )

    return relationshipsRaw
      .filter((row): row is NonNullable<typeof row> => row != null)
      .map((row): ActorRelationship => {
        // Coerce affects field - check if it's a valid object
        const rawAffects = row.affects
        const affects =
          rawAffects &&
          typeof rawAffects === 'object' &&
          !Array.isArray(rawAffects)
            ? (rawAffects as Record<string, number>)
            : undefined

        // Coerce date fields
        const rawCreatedAt = row.createdAt
        const rawUpdatedAt = row.updatedAt

        return {
          id: String(row.id ?? ''),
          actor1Id: String(row.actor1Id ?? ''),
          actor2Id: String(row.actor2Id ?? ''),
          relationshipType: String(
            row.relationshipType ?? 'acquaintances',
          ) as ActorRelationship['relationshipType'],
          strength: Number(row.strength ?? 0),
          sentiment: Number(row.sentiment ?? 0),
          isPublic: Boolean(row.isPublic),
          history: row.history ? String(row.history) : undefined,
          affects,
          createdAt: toDate(
            rawCreatedAt instanceof Date
              ? rawCreatedAt
              : String(rawCreatedAt ?? ''),
          ),
          updatedAt: toDate(
            rawUpdatedAt instanceof Date
              ? rawUpdatedAt
              : String(rawUpdatedAt ?? ''),
          ),
        }
      })
  }

  /**
   * Get specific relationship between two actors
   */
  static async getRelationship(
    actor1Id: string,
    actor2Id: string,
  ): Promise<ActorRelationship | null> {
    const relationshipRaw = await db
      .select()
      .from(actorRelationships)
      .where(
        or(
          and(
            eq(actorRelationships.actor1Id, actor1Id),
            eq(actorRelationships.actor2Id, actor2Id),
          ),
          and(
            eq(actorRelationships.actor1Id, actor2Id),
            eq(actorRelationships.actor2Id, actor1Id),
          ),
        ),
      )
      .limit(1)

    const row = relationshipRaw[0]
    if (!row) return null

    // Coerce affects field - check if it's a valid object
    const rawAffects = row.affects
    const affects =
      rawAffects && typeof rawAffects === 'object' && !Array.isArray(rawAffects)
        ? (rawAffects as Record<string, number>)
        : undefined

    // Coerce date fields
    const rawCreatedAt = row.createdAt
    const rawUpdatedAt = row.updatedAt

    return {
      id: String(row.id ?? ''),
      actor1Id: String(row.actor1Id ?? ''),
      actor2Id: String(row.actor2Id ?? ''),
      relationshipType: String(
        row.relationshipType ?? 'acquaintances',
      ) as ActorRelationship['relationshipType'],
      strength: Number(row.strength ?? 0),
      sentiment: Number(row.sentiment ?? 0),
      isPublic: Boolean(row.isPublic),
      history: row.history ? String(row.history) : undefined,
      affects,
      createdAt: toDate(
        rawCreatedAt instanceof Date
          ? rawCreatedAt
          : String(rawCreatedAt ?? ''),
      ),
      updatedAt: toDate(
        rawUpdatedAt instanceof Date
          ? rawUpdatedAt
          : String(rawUpdatedAt ?? ''),
      ),
    }
  }
}
